# Generated by Django 4.2.4 on 2023-08-05 12:16

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_review_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('src', models.ImageField(blank=True, null=True, upload_to=api.models.category_images_directory_path)),
                ('alt', models.CharField(default='There should be an image of the category', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('src', models.ImageField(blank=True, null=True, upload_to=api.models.category_images_directory_path)),
                ('alt', models.CharField(default='There should be an image of the category', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
