# Generated by Django 4.2.4 on 2023-08-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='src',
            field=models.CharField(default='1.svg', max_length=100),
        ),
    ]
