# Generated by Django 4.2.4 on 2023-08-05 16:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.category_images_directory_path),
        ),
    ]
