# Generated by Django 4.2.4 on 2023-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='dateFrom',
            field=models.DateTimeField(),
        ),
    ]
