# Generated by Django 4.2.4 on 2023-08-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_alter_basket_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveSmallIntegerField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.DecimalField(choices=[(1, 'Online'), (2, 'Cash at the office'), (3, 'Bank card at the office'), (4, 'Credit')], decimal_places=0, max_digits=1)),
                ('status', models.DecimalField(choices=[(1, 'accepted'), (2, 'assembly'), (3, 'delivery'), (4, 'completed')], decimal_places=0, max_digits=1)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('products', models.ManyToManyField(related_name='orders', to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
