# Generated by Django 4.2.4 on 2023-08-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.DecimalField(choices=[(1, 'Online'), (2, 'Cash at the office'), (3, 'Bank card at the office'), (4, 'Credit')], decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.DecimalField(choices=[(1, 'accepted'), (2, 'assembly'), (3, 'delivery'), (4, 'completed')], decimal_places=0, default=1, max_digits=1),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
