# Generated by Django 4.2.4 on 2023-08-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_order_payment_type_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
