# Generated by Django 4.2.4 on 2023-08-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Cash', 'Cash at the office'), ('Card', 'Bank card at the office'), ('Credit', 'Credit')], default='Online', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('In assembly', 'Assembly'), ('In delivery', 'Delivery'), ('Completed', 'Completed')], default='Accepted', max_length=30),
        ),
    ]
