# Generated by Django 4.2.4 on 2023-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_order_payment_type_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('assembly', 'Assembly'), ('delivery', 'Delivery'), ('completed', 'Completed')], default='Accepted', max_length=30),
        ),
    ]
