# Generated by Django 4.2.4 on 2023-08-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online', 'online'), ('cash', 'cash at the office'), ('card', 'bank card at the office'), ('credit', 'credit')], default='Online', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('assembly', 'assembly'), ('delivery', 'delivery'), ('completed', 'completed')], default='Accepted', max_length=30),
        ),
    ]
