# Generated by Django 4.2.4 on 2023-09-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_order_email_order_fullname_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
