# Generated by Django 4.2.4 on 2023-09-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='phone',
        ),
    ]
