# Generated by Django 4.2.4 on 2023-09-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_temporarybasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ManyToManyField(to='api.subcategory'),
        ),
    ]
