# Generated by Django 4.2.4 on 2023-09-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_profileimage_alt_alter_subcategory_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='accepted', max_length=90),
        ),
    ]
